### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by FilipZawada** [Skycatch/node-box#11]
Can you specify `node-box` license please? MIT license would be ideal :+1: 

Cheers,
Filip

**Comment by srt32** [comment]
:+1:

**Comment by allisonfong** [comment]
:+1:

**Comment by FilipZawada** [comment]
@lyaunzbe Any thoughts? We will have to resign from this lib if that's not solved unfortunately.

**Comment by lyaunzbe** [comment]
MIT license has been added. Thank you!
